# Generated by Django 5.1.4 on 2025-01-21 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время доставки'),
        ),
    ]
