# Generated by Django 5.1.4 on 2025-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_delivery_address_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.TextField(blank=True, default='', verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(verbose_name='Время доставки'),
        ),
    ]
